---
version: 2.1

executors:
  golang:
    docker:
    - image: circleci/golang:1.14

jobs:
  build:
    executor: golang

    steps:
    - add_ssh_keys
    - checkout
    - run: echo $PATH
    - run: go mod download
    - run: curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | BINDIR=/home/circleci/.local/bin sh
    - run: make -C stuff style
    - run: make -C stuff test
    - run: cd stuff && goreleaser release --skip-publish --snapshot
    - store_artifacts:
        path: stuff/dist

  release:
    executor: golang

    steps:
    - add_ssh_keys
    - checkout
    - run: go mod download
    - run: curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | BINDIR=/home/circleci/.local/bin sh
    - run: cd stuff && goreleaser release

workflows:
  version: 2
  stuff:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - release:
        requires:
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
