name: CI

on:
  push:
    branches:
    - master
    - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ["1.20.x", "1.21.x"]

    name: Build and Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
          check-latest: true
      - run: make -C stuff style
      - run: make -C stuff test
      - uses: goreleaser/goreleaser-action@v5
        with:
          workdir: stuff
          version: latest
          args: release --skip-publish --snapshot
      - uses: actions/upload-artifact@v4
        with:
          name: stuff
          path: stuff/stuff

  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          check-latest: true
      - uses: golangci/golangci-lint-action@v3.7.0

  publish-release:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          check-latest: true
      - uses: goreleaser/goreleaser-action@v5
        with:
          workdir: stuff
          version: latest
          args: release
