name: CI

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    name: Build and Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true
      - run: make -C stuff style
      - run: make -C stuff test
      - uses: goreleaser/goreleaser-action@v4
        with:
          workdir: stuff
          version: latest
          args: release --skip-publish --snapshot
      - uses: actions/upload-artifact@v3
        with:
          name: stuff
          path: stuff/stuff

  publish-release:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          workdir: stuff
          version: latest
          args: release
